server:
  port: 8070
  
spring:
  zipkin:
    baseUrl: http://zipkin:9411
  boot:
    admin:
      context-path: /admin
  cloud:
    loadbalancer:
       ribbon:
        enabled: false
eureka:
  instance:
    hostname: eurekaserver
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
   
